#!/usr/bin/bash
#----------------------------------------------------------------------------#
#  Name           potd_unsplash                                              #
#                                                                            #
#  Description    Get daily or random picture from unsplash.com              #
#                 (http://source.unsplash.com/....)                          #
#                                                                            #
#                 Unsplash return image content an not image uri             #
#                                                                            #
#  Input          $1: file to use as backgound   $2: screen resolution       #
#                 file to use as backgound                                   #
#----------------------------------------------------------------------------#

function potd_unsplash()
{
	local __wall=$1
	local potd=$(mktemp /tmp/potd.XXXXXXXX)
	local UN_URL="https://source.unsplash.com"
	local un_res=$2
	local ret=1
	local url=""

	[ -v DEBUG ] && echo "unsplash.com"

	case "$(shuf -e random daily -n 1)" in
		"daily") printf -v url "%s/%s/daily" ${UN_URL} ${un_res} ;;
		"random") printf -v url "%s/random/%s" ${UN_URL} ${un_res} ;;
	esac
	[ -v DEBUG ] && echo "$url"
# curl need --location because unsplash return e redirect page
  	curl --silent --location --output "$potd" "$url"
	ret=$?
	[ $ret -eq 0 ] && mv "$potd" $__wall || rm "$potd"
	return $ret
}

[ -v DEBUG ] && potd_unsplash potd 1600x900 || potd_unsplash "$@"
exit $?
